name: Daily ChatGPT Commit

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9 AM UTC

jobs:
  daily_chatgpt_commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openai

      - name: Generate commit message with GPT-4.5-preview
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -c "
import openai
import os
import datetime

openai.api_key = os.getenv('OPENAI_API_KEY')

response = openai.ChatCompletion.create(
    model='gpt-4.5-preview',
    messages=[
        {'role': 'system', 'content': 'You are generating daily commit messages for a mobile application project. The app ingests webcam video to analyze parking lot occupancy and predict optimal visitation times. Each commit message should briefly describe daily updates, such as improvements to webcam integration, predictive modeling, UI/UX enhancements, performance optimizations, or feature updates.'}
    ]
)

commit_message = response.choices[0].message.content.strip()

with open('daily_log.txt', 'a') as f:
    timestamp = datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
    f.write(f'{timestamp}: {commit_message}\n')

print(f'COMMIT_MESSAGE={commit_message}' >> os.environ['GITHUB_ENV'])
"

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_log.txt
          git commit -m "${{ env.COMMIT_MESSAGE }}"
          git push origin main
