name: Daily ChatGPT Commit

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9 AM UTC
  workflow_dispatch:

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install openai

      - name: Generate commit message
        id: generate_message
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          COMMIT_MESSAGE=$(python scripts/daily_commit.py)
          echo "COMMIT_MESSAGE=$(python scripts/daily_commit.py)" >> $GITHUB_ENV

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_log.txt
          git commit -m "${{ env.COMMIT_MESSAGE }}" || echo "No changes to commit"
          git push origin AUTO
